### Add a dog
POST http://localhost:4649/orders
Content-Type: application/json

{
    "_id": "c",
    "date": "220309",
    "isShipped": false,
    "matchStock": true
}

### Get an order from an specific date
GET http://localhost:4649/orders?date=220311

### Get all orders
GET http://localhost:4649/orders/

### Delete an order
DELETE http://localhost:4649/orders/a

### Patch an order
PATCH http://localhost:4649/orders/a
Content-Type: application/json

{
    "isShipped": true
}