### PRODUCT METHODS
### Create a new product
POST http://localhost:4649/products
Content-Type: application/json

{
    "name": "Rubber Duck",
    "stock": 100,
    "price": 5.00,
    "imageUrl":"images/rubber-duck.jpg"
}

### Get all products
GET http://localhost:4649/products

### Get all products that match stock
GET http://localhost:4649/products?matchStock=true

### Get all products that match stock
GET http://localhost:4649/products?numberOfItems=0

### Patch a product
PATCH http://localhost:4649/products/m
Content-Type: application/json

{
    "numberOfItems": "0"
}

### Delete an order
DELETE http://localhost:4649/products/622e6bfe9145c5af958ffb31